export enum IssueType {
  SENIORITY_MISMATCH = 'SENIORITY_MISMATCH',
  LOW_MATCH = 'LOW_MATCH',
  LOW_RESPONSE_RATE = 'LOW_RESPONSE_RATE',
  LOW_DISCIPLINE = 'LOW_DISCIPLINE',
  STRATEGY_INCONSISTENT = 'STRATEGY_INCONSISTENT',
  GEOGRAPHIC_FRICTION = 'GEOGRAPHIC_FRICTION',
}
